theme: 

url    : "https://nowjiin.github.io/likelionsku"
baseurl: ""

title      : LikeLionSKU
email      : your-email@example.com
description: "LikeLionSKU 홈페이지"
author     : LIKELIONSKU 11TH LEAD
#logo:     #optional, defaults to site title
  #path: assets\img\lionlogo-1024.png
  #height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: G-9T09G5TY4D

collections:
  portfolio:

markdown: kramdown